### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by woolninesun** [blovemaple/mahjong#2]
請問該怎麼 build 這個 project? 有沒有比較詳細的步驟？感謝！

**Comment by blovemaple** [comment]
@WooLNinesun 用maven编译后用java运行jar包即可。
1. 安装maven最新版本和jdk 9以上版本
2. 在源码根目录下执行`mvn build`
3. 在target目录下执行`java -jar mahjong-0.0.1-SNAPSHOT-jar-with-dependencies.jar`

**Comment by woolninesun** [comment]
ok 感謝！
